### ISSUE TITLE
Pester to do.oo3 -> text?

### ISSUE THREAD

**Issue by hmijail** [nriley/Pester#17]
I'm wondering about helping a bit, but I can't even check the To Do list without using OmniOutliner. There is a 14-day trial, but a longer-term solution would be better.

So, would you consider converting the .oo3 file to some other, freely accessible, format? (I could do it myself and send a pull request, but what kind of format would you like?)

**Comment by nriley** [comment]
On Tue, Sep 29, 2015 at 12:41:59AM -0700, Horacio Mijail Antón Quiles wrote:
> I'm wondering about helping a bit, but I can't even check the To Do
> list without using OmniOutliner. There is a 14-day trial, but a
> longer-term solution would be better.
> 
> So, would you consider converting the .oo3 file to some other,
> freely accessible, format? (I could do it myself and send a pull
> request, but what kind of format would you like?)

I converted it to HTML and checked it in, with the intention that this
will be read-only.  I will see about scripting this so it
automatically converts every time I change it.  For now, I'll keep it
up to date with any changes you make.  It's just a lot less overhead
than trying to deal with an issue tracker, and the vast majority of
what's in there is feature ideas I will probably never get to.

Also, let me know if anything in there doesn't make sense and I can
try to clarify.

Thanks for your interest!

--Nicholas

**Comment by nriley** [comment]
I've linked to a HTML rendering (through rawgit.com) from the README, and written the aforementioned script, which now also automates my update commits.  Should be enough for now, and probably something I should have done a while ago!

[Here's the script](https://gist.github.com/nriley/fb2abd6f06f5f2619fd6), which will save, export and commit for me.
