### ISSUE TITLE
Dropped OS X 10.8 -> drop Growl?

### ISSUE THREAD

**Issue by hmijail** [nriley/Pester#18]
According to the To Do, in Beta 21 only 10.9 and later will be supported. That means that Notification Center will always be there. 

Meanwhile, Growl seems to have died; they don't even mention 10.10 and there is no blog activity since 2013.

So, is there a plan to drop Growl, or at least disable compilation of the parts that depend on it? It would (slightly) simplify the process to get into Pester development.

I could try it myself, but I am not familiar with Xcode and Cocoa, so I don't know how should I go about it. Xcode build target? some config.h? some -D compilation flag and #ifdef'ing? ... any example to look at?

**Comment by nriley** [comment]
On Tue, Sep 29, 2015 at 12:54:51AM -0700, Horacio Mijail Antón Quiles wrote:
> According to the To Do, in Beta 21 only 10.9 and later will be
> supported. That means that Notification Center will always be there.
> 
> Meanwhile, Growl seems to have died; they don't even mention 10.10
> and there is no blog activity since 2013.
> 
> So, is there a plan to drop Growl, or at least disable compilation
> of the parts that depend on it? It would (slightly) simplify the
> process to get into Pester development.

Short answer: no.

Long answer: download http://growl.cachefly.net/Growl-2.0.1-SDK.zip;
there are instructions in the README on where to put Growl.framework
prior to compilation (note that you want the old version, 1.2.3).  I
should probably link to this from the README as well.

Growl development is not dead, it's just very slow thanks to the
people working on it having other jobs.  I'd love to drop it, but
unfortunately OS X notifications still don't have features I need.
Displaying my *own* notifications and not using Growl would be one
option, but it's a very low priority at the moment.

--Nicholas

**Comment by nriley** [comment]
I've updated the README to make it clearer how to get the version of the Growl framework that Pester needs.  This should be enough for now.
